[package]
name = "terminal"
version = "0.1.0"
authors = ["Jeremy Soller <jeremy@system76.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
colored = "2.0"
cosmic-text = { path = "../../" }
env_logger = "0.10"
fontdb = "0.13"
log = "0.4"
